//Copyright 2026 Team Tofunut. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "WetClothing/Foundation/Resources/DWCEditorAccountedMemory.h"

struct FDWCTransparencySourceHitStats
{
    int32 PriorityIndex = INDEX_NONE;
    int32 MaterialSlotIndex = INDEX_NONE;
    FName MaterialSlotName;
    int32 SourceBakeResolution = 0;
    int32 HitCount = 0;
};

/**
 * Compact editor-authoring surface generated by Transparency Stage 2.
 *
 * RG stores the inner material normal reoriented into the target surface's
 * tangent frame, B stores inner Metallic, and A stores valid source coverage.
 * This packed payload is an editor-only input to reveal color correction and
 * the future runtime Reveal Normal build; it is not itself a runtime contract.
 */
struct FDWCTransparencyRevealSurfaceAuthoringPayload
{
    FIntPoint Resolution = FIntPoint::ZeroValue;
    TArray<FColor> PackedPixels;

    void Init(FIntPoint InResolution, FColor InitialValue);
    void SetNumUninitialized(FIntPoint InResolution);
    void Reset();

    bool IsValid() const;
    bool IsValidForResolution(FIntPoint ExpectedResolution) const;
    int32 Num() const { return PackedPixels.Num(); }
    FColor* GetData() { return PackedPixels.GetData(); }
    const FColor* GetData() const { return PackedPixels.GetData(); }
    FColor& operator[](int32 Index) { return PackedPixels[Index]; }
    const FColor& operator[](int32 Index) const { return PackedPixels[Index]; }
    const TArray<FColor>& GetPackedPixels() const { return PackedPixels; }

    FVector3f DecodeRevealNormal(int32 PixelIndex) const;
    /** Converts packed editor RGBA into coverage-weighted runtime normal RG. */
    static FColor EncodeRuntimeRevealNormal(FColor PackedAuthoringPixel);
    float GetInnerMetallic(int32 PixelIndex) const;
    float GetSourceCoverage(int32 PixelIndex) const;
    bool HasValidSource(int32 PixelIndex) const;
    uint64 GetAllocatedBytes() const;
};

/**
 * Canonical immutable output of Transparency Stage 2.
 *
 * Auto-map generation, reveal correction, final alpha authoring, preview, and
 * bake all share this payload. Keeping the contract in Pipeline prevents
 * downstream systems from depending on the AutoMap producer implementation.
 */
struct FDWCTransparencySourcePayload
{
    static constexpr uint16 InvalidOuterIslandID = MAX_uint16;

    static bool CanEncodeOuterIslandID(const int32 IslandID)
    {
        return IslandID >= 0 && IslandID < static_cast<int32>(InvalidOuterIslandID);
    }

    static uint16 EncodeOuterIslandID(const int32 IslandID)
    {
        return CanEncodeOuterIslandID(IslandID)
            ? static_cast<uint16>(IslandID)
            : InvalidOuterIslandID;
    }

    static int32 DecodeOuterIslandID(const uint16 IslandID)
    {
        return IslandID != InvalidOuterIslandID
            ? static_cast<int32>(IslandID)
            : INDEX_NONE;
    }

    static bool MatchesOuterIslandID(const uint16 EncodedIslandID, const int32 IslandID)
    {
        return IslandID == INDEX_NONE ||
            (CanEncodeOuterIslandID(IslandID) && EncodedIslandID == static_cast<uint16>(IslandID));
    }

    /** Resolves the texture-space island used consistently by hover, live paint, and stroke replay. */
    int32 ResolveOuterIslandIDAtUV(
        const FVector2D& PositionUV,
        int32 FallbackUVIslandID,
        bool bWrap) const;

    FGuid LayerGuid;
    int32 MaterialSlotIndex = INDEX_NONE;
    int32 UVChannelIndex = 0;
    int32 LODIndex = 0;
    /** Canonical target-space extent shared by Stages 2, 3, 4 and runtime outputs. */
    FIntPoint Resolution = FIntPoint::ZeroValue;
    /** Resolver identity captured with Resolution at the request boundary. */
    FString OutputResolutionIdentity;
    FString BuildSignature;
    /** Material-surface identity captured by the same canonical signature pass. */
    FString MaterialBakeSignature;
    int32 OuterSampleCount = 0;
    int32 ValidHitCount = 0;
    int32 NoHitCount = 0;
    int32 OverlappedUVPixelCount = 0;
    TArray<FColor> InnerColorBuffer;
    FDWCTransparencyRevealSurfaceAuthoringPayload RevealSurfaceAuthoring;
    TArray<uint8> AutoAlphaBuffer;
    /** Fractional target-surface texel coverage: 0 is outside, 255 is fully covered. */
    TArray<uint8> OuterCoverageBuffer;
    TArray<uint16> OuterIslandIDBuffer;
    TBitArray<> ValidHitBuffer;
    TArray<float> HitDistanceBuffer;
    TArray<int16> SourcePriorityBuffer;
    TArray<FDWCTransparencySourceHitStats> SourceStats;

    // A restored baked baseline contains final authoring state. Generated
    // source payloads contain the pre-final automatic alpha instead.
    bool bIsFinalBakedBaseline = false;

    int32 BaselineStrokeCount = 0;
    FGuid BaselineBakeGuid;

    /**
     * Attached after this payload becomes immutable. Every shared consumer
     * then keeps the same PreviewWorkspaceCPU reservation alive.
     */
    TSharedPtr<FDWCEditorAccountedMemory, ESPMode::ThreadSafe> PersistentMemoryAccount;

    uint64 GetAllocatedBytes() const
    {
        return static_cast<uint64>(sizeof(FDWCTransparencySourcePayload)) +
            static_cast<uint64>(BuildSignature.GetAllocatedSize()) +
            static_cast<uint64>(MaterialBakeSignature.GetAllocatedSize()) +
            static_cast<uint64>(OutputResolutionIdentity.GetAllocatedSize()) +
            static_cast<uint64>(InnerColorBuffer.GetAllocatedSize()) +
            RevealSurfaceAuthoring.GetAllocatedBytes() +
            static_cast<uint64>(AutoAlphaBuffer.GetAllocatedSize()) +
            static_cast<uint64>(OuterCoverageBuffer.GetAllocatedSize()) +
            static_cast<uint64>(OuterIslandIDBuffer.GetAllocatedSize()) +
            static_cast<uint64>(ValidHitBuffer.GetAllocatedSize()) +
            static_cast<uint64>(HitDistanceBuffer.GetAllocatedSize()) +
            static_cast<uint64>(SourcePriorityBuffer.GetAllocatedSize()) +
            static_cast<uint64>(SourceStats.GetAllocatedSize());
    }
};
