//Copyright 2026 Team Tofunut. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"

/** Shared naming and path helpers for assets generated by Dynamic Wet Clothes. */
namespace DWCGeneratedAssetPaths
{
    inline constexpr const TCHAR* RootFolderName = TEXT("DWCGenerated");
    inline constexpr const TCHAR* SharedSurfaceTextureFolder = TEXT("/Game/DWCGenerated/Shared/SurfaceTextures");

    inline FString MakeAssetRoot(const FString& OwningFolder, const FString& AssetName)
    {
        return OwningFolder / RootFolderName / AssetName;
    }
}
