#include "WetClothingSurfaceWaterUVGenerator.h"

#include "DataAssets/WetClothingAsset.h"
#include "AssetCompilingManager.h"
#include "Engine/SkeletalMesh.h"
#include "MeshDescription.h"
#include "MeshUVChannelInfo.h"
#include "SkeletalMeshAttributes.h"
#include "WetClothing/Common/Analysis/WetClothingAssetMeshAnalyzer.h"
#include "WetClothing/WrinkleEdit/UV/WetWrinkleUVChannelGenerator.h"

FWetClothingSurfaceWaterUVGenerationResult FWetClothingSurfaceWaterUVGenerator::Generate(
    UWetClothingAsset* Asset,
    int32 LODIndex,
    int32 SourceUVChannelIndex,
    int32 PreferredUVChannelIndex,
    int32 Resolution,
    int32 PaddingPixels,
    bool bAllowOverwriteExistingChannel,
    double TargetTexelsPerCentimeter)
{
    FWetClothingSurfaceWaterUVGenerationResult Result;
    if (!Asset || !Asset->TargetMesh)
    {
        Result.Message = TEXT("Surface Water UV generation requires a Wet Clothing Asset with a target mesh.");
        return Result;
    }
    if (PreferredUVChannelIndex < 0 || PreferredUVChannelIndex >= MAX_TEXCOORDS)
    {
        Result.Message = FString::Printf(
            TEXT("Skeletal Mesh Surface Water UV channel must be between 0 and %d. Requested channel: %d."),
            MAX_TEXCOORDS - 1,
            PreferredUVChannelIndex);
        return Result;
    }

    //1. See If there is any Wettable Slot here
    TArray<int32> WettableMaterialSlots;
    for (const FWetClothingWettableMaterialSlotState& Slot : Asset->PartData.EditableWetPartData.WettableMaterialSlots)
    {
        if (Slot.bIsWettableSlot && Slot.MaterialSlotIndex != INDEX_NONE)
        {
            WettableMaterialSlots.AddUnique(Slot.MaterialSlotIndex);
        }
    }
    WettableMaterialSlots.Sort();
    if (WettableMaterialSlots.IsEmpty())
    {
        Result.Message = TEXT("No Wettable Material Slots are enabled.");
        return Result;
    }

    double MaximumSharedTexelsPerCentimeter = 0.0;
    FString DensityError;
    if (!FWetWrinkleUVChannelGenerator::CalculateSharedWorldTexelDensity(
            Asset->TargetMesh,
            LODIndex,
            Resolution,
            PaddingPixels,
            SourceUVChannelIndex,
            WettableMaterialSlots,
            MaximumSharedTexelsPerCentimeter,
            DensityError))
    {
        Result.Message = FString::Printf(TEXT("Surface Water UV density analysis failed: %s"), *DensityError);
        return Result;
    }

    const double SharedTexelsPerCentimeter = TargetTexelsPerCentimeter > 0.0
        ? FMath::Min(TargetTexelsPerCentimeter, MaximumSharedTexelsPerCentimeter)
        : MaximumSharedTexelsPerCentimeter;
    Result.GeneratedTexelsPerCentimeter = SharedTexelsPerCentimeter;

    //2. See If Target UVChannel is Safe
    
    FSurfaceWaterSimulationSettings& SurfaceSettings = Asset->SurfaceWaterSettings;
    int32 TargetUVChannelIndex = PreferredUVChannelIndex;
    const bool bTargetChannelGeneratedByDWCBefore = SurfaceSettings.bHasGeneratedSurfaceWaterUV && //Was Surface Water UV Generated by DWC Before? 
                                                 SurfaceSettings.GeneratedSurfaceWaterUVChannelIndex == TargetUVChannelIndex;//Is Target Channel Same with Before
    //2.1 If DWC Never Made UVChannel Before and is unable to Make it
    if (!bTargetChannelGeneratedByDWCBefore && !bAllowOverwriteExistingChannel)
    {
        //Get LODIndex MeshDescription
        FMeshDescription* MeshDescription = Asset->TargetMesh->GetMeshDescription(LODIndex);
        if (!MeshDescription)
        {
            Result.Message = FString::Printf(TEXT("The target skeletal mesh has no editable Mesh Description for LOD %d."), LODIndex);
            return Result;
        }
        //Gonna See MeshDescription as SkeletalMeshAttribute
        FSkeletalMeshAttributes Attributes(*MeshDescription);
        Attributes.Register();
        //If TargetUVChannelIndex smaller then MaxChannel.
        if (TargetUVChannelIndex < Attributes.GetVertexInstanceUVs().GetNumChannels())
        {
            Result.Message = FString::Printf(
                TEXT("Requested Surface Water UV channel %d already exists. Enable 'Allow Overwrite Existing UV Channel' to replace it, or select an unused channel."),
                TargetUVChannelIndex);
            return Result;
        }
    }
    
    //2.2 If DWC Made UVChannel Before |OR!| Can Overwrite it
    bool bCanOverwriteTargetChannel = (bTargetChannelGeneratedByDWCBefore || bAllowOverwriteExistingChannel) && TargetUVChannelIndex != INDEX_NONE;

    Asset->Modify();
    //For Each Wettable Wettable Slots
    for (int32 MaterialSlotIndex : WettableMaterialSlots)
    {
        //Make New UV Channel(1Slot = 1Texture) And Push New UV Channel Coordinate to Vertices 
        const FWetWrinkleUVChannelGenerationResult SlotResult = FWetWrinkleUVChannelGenerator::GenerateForSkeletalMesh(
            Asset->TargetMesh,
            LODIndex,
            Resolution,
            PaddingPixels,
            SourceUVChannelIndex,
            TargetUVChannelIndex,
            bCanOverwriteTargetChannel,
            MaterialSlotIndex,
            SharedTexelsPerCentimeter);
        if (!SlotResult.bSucceeded)
        {
            Result.Message = FString::Printf(TEXT("Surface Water UV generation failed for material slot %d: %s"), MaterialSlotIndex, *SlotResult.Message);
            return Result;
        }

        FAssetCompilingManager::Get().FinishCompilationForObjects({Asset->TargetMesh.Get()});

        if (Result.GeneratedSlotCount == 0)
        {
            TargetUVChannelIndex = SlotResult.UVChannelIndex;
            bCanOverwriteTargetChannel = true;
        }
        else if (SlotResult.UVChannelIndex != TargetUVChannelIndex)
        {
            Result.Message = TEXT("Surface Water UV generation selected inconsistent destination channels across material slots.");
            return Result;
        }

        FSurfaceWaterMaterialSlotData* SlotData = SurfaceSettings.SurfaceWaterMaterialSlots.FindByPredicate(
            [MaterialSlotIndex](const FSurfaceWaterMaterialSlotData& Candidate)
            {
                return Candidate.MaterialSlotIndex == MaterialSlotIndex;
            });
        if (!SlotData)
        {
            SlotData = &SurfaceSettings.SurfaceWaterMaterialSlots.AddDefaulted_GetRef();
            SlotData->MaterialSlotIndex = MaterialSlotIndex;
        }
        SlotData->bEnabled = true;
        SlotData->UVChannelIndex = TargetUVChannelIndex;
        SlotData->BakedFlowMap.bIsValid = false;
        SlotData->BakedFlowMap.BuildSignature.Reset();

        ++Result.GeneratedSlotCount;
        Result.GeneratedIslandCount += SlotResult.PackedIslandCount;
    }

    FAssetCompilingManager::Get().FinishCompilationForObjects({Asset->TargetMesh.Get()});
    for (int32 MaterialSlotIndex : WettableMaterialSlots)
    {
        TArray<FWetClothingAssetUVIsland> Islands;
        FString ValidationError;
        if (!FWetClothingAssetMeshAnalyzer::BuildMaterialSlotUVIslands(
                Asset->TargetMesh,
                LODIndex,
                TargetUVChannelIndex,
                MaterialSlotIndex,
                Islands,
                &ValidationError))
        {
            Result.Message = FString::Printf(TEXT("Generated Surface Water UV validation failed for material slot %d: %s"), MaterialSlotIndex, *ValidationError);
            return Result;
        }

        bool bHasNonDegenerateUVTriangle = false;
        for (const FWetClothingAssetUVIsland& Island : Islands)
        {
            for (const FWetClothingAssetUVTriangle& Triangle : Island.UVTriangles)
            {
                const FVector2D A = Triangle.UVs[1] - Triangle.UVs[0];
                const FVector2D B = Triangle.UVs[2] - Triangle.UVs[0];
                if (FMath::Abs(A.X * B.Y - A.Y * B.X) > 1.e-8)
                {
                    bHasNonDegenerateUVTriangle = true;
                    break;
                }
            }
            if (bHasNonDegenerateUVTriangle) break;
        }
        if (!bHasNonDegenerateUVTriangle)
        {
            Result.Message = FString::Printf(TEXT("Generated Surface Water UV channel %d contains only degenerate triangles for material slot %d."), TargetUVChannelIndex, MaterialSlotIndex);
            return Result;
        }
    }

    SurfaceSettings.UVChannelIndexToConstruct = TargetUVChannelIndex;
    SurfaceSettings.bHasGeneratedSurfaceWaterUV = true;
    SurfaceSettings.GeneratedSurfaceWaterUVChannelIndex = TargetUVChannelIndex;
    SurfaceSettings.GeneratedSurfaceWaterSourceUVChannelIndex = SourceUVChannelIndex;
    SurfaceSettings.GeneratedSurfaceWaterUVBuildGuid = FGuid::NewGuid();

    FString PrecomputeError;
    if (!Asset->RebuildPrecomputedSimulationData(&PrecomputeError, LODIndex))
    {
        Result.Message = FString::Printf(
            TEXT("Surface Water UV generation succeeded, but Wet Clothing runtime data rebuild failed: %s"),
            *PrecomputeError);
        return Result;
    }
    Asset->MarkPackageDirty();

    Result.bSucceeded = true;
    Result.UVChannelIndex = TargetUVChannelIndex;
    Result.Message = FString::Printf(
        TEXT("Generated Surface Water UV channel %d for %d Wettable Material Slot(s), with %d independently packed island(s) at a shared density of %.3f texels/cm. Flow Maps must be baked again."),
        TargetUVChannelIndex,
        Result.GeneratedSlotCount,
        Result.GeneratedIslandCount,
        Result.GeneratedTexelsPerCentimeter);
    return Result;
}
